#!/usr/bin/env bash

while getopts "s:" opt; do
    case "$opt" in
        s) settings_file=$OPTARG ;;
    esac
done
shift $((OPTIND - 1))

infile=$1
outfile=$2

if [[ -z "$settings_file" ]]; then
    settings_file_name="plot-settings"

    for path in "./$settings_file_name" "$HOME/$settings_file_name" "/etc/$settings_file_name"; do
        [[ -e "$path" ]] && settings_file="$path" && break
    done || { echo "[Error]: settings file not found." >&2; exit 1; }
fi


if [[ -z "$infile" || -z "$outfile" ]]; then
    echo "Usage: gen-hist INFILE OUTFILE.png" >&2
    exit 1
fi

data=$(grep -v "^#" "$infile" | tr " " "\t")

for i in $(seq 1 "$(nproc)"); do
    echo "$data" | cut -f1,"$((i + 1))" > hist"$i"
done

settings=$(cat "$settings_file")

gnuplot_cmd="${settings}
set output \"${outfile}\"
plot "

for i in $(seq 1 "$(nproc)"); do
    if [[ "$i" != 1 ]]; then
        gnuplot_cmd+=", "
    fi

    gnuplot_cmd+="\"hist$i\" using 1:2 title \"CPU$((i - 1))\" with histeps"
done

echo "$gnuplot_cmd" | gnuplot

rm hist*
